name       : libideviceactivation
version    : 1.0.0
release    : 2
source     :
    - http://www.libimobiledevice.org/downloads/libideviceactivation-1.0.0.tar.bz2 : 1da81de80020ce038b683330747875ebc5040c6476d4f44784975d08ab1f5aee
license    : GPL-3.0
summary    : A library to manage the activation process of Apple iOS devices.
description: |
    A library to manage the activation process of Apple iOS devices.
builddeps  :
    - usbmuxd
    - pkgconfig(libcurl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libplist)
    - pkgconfig(libimobiledevice-1.0)
rundeps : 
    - ifuse
    - usbmuxd
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
